AREA =(
	('ME','Médico da Estratégia de Saúde da Família'),
	('EN','Enfermeiro(a) da Estratégia de Saúde da Família'),
	('DE','Dentista da Estratégia de Saúde da Família'),
    ('TE','Técnico em Enfermagem'),
    ('AX','Auxiliar em Saúde Bucal'),
    ('TB','Técnico em Saúde Bucal'),
    ('AC','Agente Comunitário de Saúde'),
    ('AE','Agente de Endemias'),
    ('SC','Secretário(a) da Saúde'),
    ('AB','Coordenador da Atenção Básica'),
    ('SB','Coordenador da Saúde Bucal'),
    ('VS','Coordenador da Vigilância Sanitária'),
    ('VE','Coordenador da Vigilância Epidemiológica'),
    ('VA','Coordenador da Vigilância Ambiental'),
    ('AT','Atendente'),
    ('FS','Fisioterapeuta'),
    ('TA','Terapeuta ocupacional'),
    ('FN','Fonoaudiólogo(a)'),
    ('PI','Psiquiatra'),
    ('NT','Nutricionista'),
    ('PS','Psicólogo(a)'),
    ('EF','Educador(a) Físico(a)'),
    ('PP','Psicopedagogo(a)'),
)

