# Generated by Django 4.2 on 2026-01-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(error_messages={'blank': 'O CPF é obrigatório.', 'unique': 'Este CPF já está cadastrado.'}, max_length=14, unique=True, verbose_name='CPF')),
                ('carga_horaria_diaria', models.DurationField(blank=True, null=True)),
                ('carga_horaria_semanal', models.DurationField(blank=True, null=True)),
                ('horario_entrada', models.TimeField(blank=True, null=True, verbose_name='Horário de Entrada')),
                ('horario_saida', models.TimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=10, verbose_name='Tolerância (minutos)')),
                ('ativo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('estabelecimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento')),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.areaatuacao')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome', 'sobrenome'],
            },
        ),
    ]
