# Generated by Django 4.2 on 2026-01-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (11) 99999-9999', max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
