# Generated by Django 4.2 on 2025-10-28 19:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='carga_horaria_diaria',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), verbose_name='Carga Horária Diária'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='carga_horaria_semanal',
            field=models.DurationField(default=datetime.timedelta(days=1, seconds=57600), verbose_name='Carga Horária Semanal'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='estabelecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estabelecimentos.estabelecimento', verbose_name='Estabelecimento'),
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-data_hora'],
            },
        ),
    ]
