# Generated by Django 4.2 on 2025-10-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profissional_carga_horaria_diaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='carga_horaria_diaria',
            field=models.TimeField(blank=True, help_text='Carga horária diária em formato HH:MM', null=True, verbose_name='Carga Horária Diária'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='carga_horaria_semanal',
            field=models.TimeField(blank=True, help_text='Carga horária semanal em formato HH:MM', null=True, verbose_name='Carga Horária Semanal'),
        ),
    ]
