# Generated by Django 4.2 on 2025-10-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_profissional_carga_horaria_diaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='carga_horaria_diaria',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='carga_horaria_semanal',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
