# Generated by Django 4.2 on 2025-10-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_profissional_carga_horaria_diaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='horas_diarias',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profissional',
            name='horas_semanais',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
