# Generated by Django 4.2 on 2025-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_profissional_horas_diarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='tolerancia_minutos',
            field=models.PositiveIntegerField(default=10, verbose_name='Tolerância (minutos)'),
        ),
    ]
