# Generated by Django 4.2 on 2026-08-13 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estabelecimentos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('horario', models.TimeField(verbose_name='Horário real')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de registro')),
                ('motivo', models.CharField(choices=[('ESQUECIMENTO', 'Esquecimento do profissional'), ('PROBLEMA_SISTEMA', 'Problema no sistema de ponto'), ('EMERGENCIA', 'Emergência/urgência médica'), ('REUNIAO', 'Reunião prolongada'), ('ATIVIDADE_EXTERNA', 'Atividade externa'), ('FALHA_EQUIPAMENTO', 'Falha no equipamento'), ('CAPACITACAO', 'Capacitação/treinamento'), ('OUTRO', 'Outro motivo')], max_length=50, verbose_name='Motivo do ajuste')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição adicional')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude (aprox.)')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude (aprox.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do ajuste')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado pelo RH')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data da confirmação')),
                ('ajustado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional')),
            ],
            options={
                'verbose_name': 'Registro Manual',
                'verbose_name_plural': 'Registros Manuais',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atraso_minutos', models.IntegerField(default=0, verbose_name='Atraso (minutos)')),
                ('saida_antecipada_minutos', models.IntegerField(default=0, verbose_name='Saída Antecipada (minutos)')),
                ('dentro_tolerancia', models.BooleanField(default=True, verbose_name='Dentro da Tolerância')),
                ('ajuste_manual', models.BooleanField(default=False, verbose_name='Ajuste Manual')),
                ('justificativa_ajuste', models.CharField(blank=True, help_text='Justificativa para o ajuste manual do registro', max_length=255, null=True, verbose_name='Justificativa do Ajuste')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o registro', null=True, verbose_name='Observações')),
                ('ajustado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ajustados', to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional')),
                ('registro_manual_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto.registromanual', verbose_name='Referência do Registro Manual')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['profissional', 'data'], name='ponto_regis_profiss_33e2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['ajuste_manual'], name='ponto_regis_ajuste__cd5aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['data', 'tipo'], name='ponto_regis_data_dbb05a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroponto',
            unique_together={('profissional', 'estabelecimento', 'data', 'tipo')},
        ),
    ]
