# Generated by Django 4.2 on 2026-01-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atraso_minutos', models.IntegerField(default=0, verbose_name='Atraso (minutos)')),
                ('saida_antecipada_minutos', models.IntegerField(default=0, verbose_name='Saída Antecipada (minutos)')),
                ('dentro_tolerancia', models.BooleanField(default=True, verbose_name='Dentro da Tolerância')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data', '-horario'],
                'unique_together': {('profissional', 'estabelecimento', 'data', 'tipo')},
            },
        ),
    ]
