# Generated by Django 4.2 on 2026-08-13 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromanual',
            name='codigo_validacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Usado nas URLs públicas de comprovante/QR Code em vez do ID sequencial.', unique=True, verbose_name='Código de validação do comprovante'),
        ),
    ]
