# Generated by Django 4.2 on 2025-10-28 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional'),
        ),
        migrations.AlterUniqueTogether(
            name='registroponto',
            unique_together={('profissional', 'estabelecimento', 'data', 'tipo')},
        ),
    ]
