# Generated by Django 4.2 on 2026-02-07 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='ajuste_manual',
            field=models.BooleanField(default=False, verbose_name='Ajuste Manual'),
        ),
        migrations.CreateModel(
            name='RegistroManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do registro')),
                ('horario', models.TimeField(verbose_name='Horário real')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo de registro')),
                ('motivo', models.CharField(choices=[('ESQUECIMENTO', 'Esquecimento de bater ponto'), ('FALHA_SISTEMA', 'Falha no sistema de ponto'), ('AUSENCIA', 'Ausência justificada'), ('OUTRO', 'Outro motivo')], max_length=50, verbose_name='Motivo do ajuste')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição adicional')),
                ('latitude', models.FloatField(default=0, verbose_name='Latitude (aprox.)')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitude (aprox.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do ajuste')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado pelo RH')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Data da confirmação')),
                ('ajustado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.profissional')),
            ],
            options={
                'verbose_name': 'Registro Manual',
                'verbose_name_plural': 'Registros Manuais',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.AddField(
            model_name='registroponto',
            name='registro_manual_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto.registromanual', verbose_name='Referência do Registro Manual'),
        ),
    ]
