# Generated by Django 4.2 on 2026-08-13 22:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_registromanual_codigo_validacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='codigo_validacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Usado nas URLs públicas de comprovante/QR Code em vez do ID sequencial.', unique=True, verbose_name='Código de validação do comprovante'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='hash_registro',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='identificador_coletor',
            field=models.CharField(choices=[('01', 'Aplicativo mobile'), ('02', 'Browser (navegador internet)'), ('03', 'Aplicativo desktop'), ('04', 'Dispositivo eletrônico'), ('05', 'Outro dispositivo eletrônico')], default='02', max_length=2),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='nsr',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='offline',
            field=models.BooleanField(default=False, help_text='Marcação feita sem conexão no momento e sincronizada depois.', verbose_name='Marcação offline'),
        ),
        migrations.AlterField(
            model_name='registromanual',
            name='codigo_validacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de validação do ajuste manual'),
        ),
    ]
