# Generated by Django 4.2 on 2026-02-09 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponto', '0002_registroponto_ajuste_manual_registromanual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='ajustado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ajustados', to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='justificativa_ajuste',
            field=models.CharField(blank=True, help_text='Justificativa para o ajuste manual do registro', max_length=255, null=True, verbose_name='Justificativa do Ajuste'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre o registro', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='registromanual',
            name='motivo',
            field=models.CharField(choices=[('ESQUECIMENTO', 'Esquecimento do profissional'), ('PROBLEMA_SISTEMA', 'Problema no sistema de ponto'), ('EMERGENCIA', 'Emergência/urgência médica'), ('REUNIAO', 'Reunião prolongada'), ('ATIVIDADE_EXTERNA', 'Atividade externa'), ('FALHA_EQUIPAMENTO', 'Falha no equipamento'), ('CAPACITACAO', 'Capacitação/treinamento'), ('OUTRO', 'Outro motivo')], max_length=50, verbose_name='Motivo do ajuste'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['profissional', 'data'], name='ponto_regis_profiss_33e2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['ajuste_manual'], name='ponto_regis_ajuste__cd5aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='registroponto',
            index=models.Index(fields=['data', 'tipo'], name='ponto_regis_data_dbb05a_idx'),
        ),
    ]
