# Generated by Django 4.2 on 2025-10-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='atraso_minutos',
            field=models.IntegerField(default=0, verbose_name='Atraso (minutos)'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='dentro_tolerancia',
            field=models.BooleanField(default=True, verbose_name='Dentro da Tolerância'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='saida_antecipada_minutos',
            field=models.IntegerField(default=0, verbose_name='Saída Antecipada (minutos)'),
        ),
    ]
