# Generated by Django 4.2 on 2026-08-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoServicoAFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsr', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('02', 'Retorno de energia/serviço'), ('07', 'Disponibilidade de serviço'), ('08', 'Indisponibilidade de serviço')], max_length=2)),
            ],
            options={
                'verbose_name': 'Evento de serviço (AFD tipo 6)',
                'verbose_name_plural': 'Eventos de serviço (AFD tipo 6)',
                'ordering': ['nsr'],
            },
        ),
        migrations.CreateModel(
            name='SequenciaNSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atual', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sequência de NSR',
                'verbose_name_plural': 'Sequência de NSR',
            },
        ),
        migrations.CreateModel(
            name='EventoFuncionarioAFD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsr', models.PositiveBigIntegerField(editable=False, unique=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_operacao', models.CharField(choices=[('I', 'Inclusão'), ('A', 'Alteração'), ('E', 'Exclusão')], max_length=1)),
                ('cpf_funcionario', models.CharField(max_length=11)),
                ('nome_funcionario', models.CharField(max_length=52)),
                ('cpf_responsavel', models.CharField(blank=True, default='', max_length=11)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.profissional')),
            ],
            options={
                'verbose_name': 'Evento de funcionário (AFD tipo 5)',
                'verbose_name_plural': 'Eventos de funcionário (AFD tipo 5)',
                'ordering': ['nsr'],
            },
        ),
    ]
